#######################################################################################
# Book settings
title     : Data Science in Practice
author    : Thomas Donoghue, Bradley Voytek, & Shannon Ellis
copyright : "2020-"
logo      : assets/logo.png

#######################################################################################
# Execution settings
execute:
  execute_notebooks           : cache

#######################################################################################
# HTML-specific settings
html:
  home_page_in_navbar         : false

# #######################################################################################
# Interact link settings
notebook_interface            : "notebook"

#######################################################################################
# Launch button settings
repository:
  url                         : https://github.com/datascienceinpractice/Site
  path_to_book                : "dsip"

binder:
  binderhub_url               : "https://mybinder.org"
  text                        : "Launch binder"

#######################################################################################
# HTML settings
html:
  favicon: assets/logo.png
  use_repository_button: true
  use_issues_button: true
  use_edit_page_button: false
